# Example3
# Сделать свое исключение и подключить к try/except

class Big_number_error(Exception):
    """Вызывается, когда входное значение больше 10 символов"""
         pass